include:
  - ia-service/infrastructure/database/docker-compose.yml
  - ia-service/infrastructure/redis/docker-compose.yml
  - ia-service/docker-compose.yml
  - report-api/docker-compose.yml
  - ia-service/streamlit-app/docker-compose.yml
